#!/usr/bin/env bash
# Mirsal fresh-server deploy — step 2/5: generate .env with fresh secrets.
#
# Writes ./.env (mode 600) with random SESSION_SECRET/CSRF_SECRET and your
# domain. Refuses to overwrite an existing .env unless --force is passed (so a
# re-run never silently rotates your secrets and invalidates live sessions).
#
# Usage:  sudo bash deploy/fresh/02-make-env.sh <domain> [--force] [--tz <TZ>]
#   e.g.  sudo bash deploy/fresh/02-make-env.sh files.example.com
#         sudo bash deploy/fresh/02-make-env.sh files.example.com --tz Europe/Berlin
set -euo pipefail

cd "$(dirname "$0")/../.."   # repo root

DOMAIN="${1:-}"
FORCE=0
TZ_VALUE="Etc/UTC"
shift || true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1 ;;
    --tz) shift; TZ_VALUE="${1:-Etc/UTC}" ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ -z "$DOMAIN" || "$DOMAIN" == --* ]]; then
  echo "Usage: sudo bash deploy/fresh/02-make-env.sh <domain> [--force] [--tz <TZ>]" >&2
  exit 2
fi

if [[ -f .env && $FORCE -ne 1 ]]; then
  echo ".env already exists. Refusing to overwrite (would rotate secrets)." >&2
  echo "Re-run with --force only if you intend to replace it." >&2
  exit 1
fi

command -v openssl >/dev/null 2>&1 || { echo "openssl not found" >&2; exit 1; }
SESSION_SECRET="$(openssl rand -hex 32)"
CSRF_SECRET="$(openssl rand -hex 32)"

umask 077
cat > .env <<EOF
# Mirsal server configuration — generated by deploy/fresh/02-make-env.sh
# Domain: ${DOMAIN}    Generated for a public-IP VPS (nginx is the TLS edge).

# SQLite DB + uploaded blobs live under the bind-mounted /app/data (see compose).
DB_PATH=/app/data/db/mirsal.db
STORAGE_DIR=/app/data/storage

# Container binds all interfaces; the compose publish 127.0.0.1:8084:8084 confines exposure.
HOST=0.0.0.0

# Fresh random secrets — never reuse another box's values.
SESSION_SECRET=${SESSION_SECRET}
CSRF_SECRET=${CSRF_SECRET}

# Absolute base URL for share links — MUST match the public HTTPS host.
PUBLIC_BASE_URL=https://${DOMAIN}

# Trust loopback + the pinned docker-gateway (compose subnet 172.31.99.0/24) so the
# app reads the real client IP from nginx's X-Forwarded-For (per-IP login limiting).
# nginx is the edge here, so it sets X-Forwarded-For to the true client.
TRUST_PROXY=loopback,172.31.99.1/32

# Argon2id tuning (defaults are fine for a small box).
ARGON_MEMORY_KIB=19456
ARGON_TIME=2
ARGON_PARALLELISM=1
ARGON_MAX_CONCURRENCY=2

TZ=${TZ_VALUE}
EOF
chmod 600 .env

echo "Wrote .env (mode 600) for ${DOMAIN}. Secrets generated fresh."
echo "Next: sudo bash deploy/fresh/03-build-run.sh"
